<tr>
<td>#</td>
<td>model</td>
<td>report_name</td>
<td>record_type</td>
<td>node_name</td>
<td>table_name</td>
<td>table_controller_exists</td>
<td>table_reporting_active</td>
<td>table_route_exists</td>
</tr>
