<tr>
<td>#</td>
<td>record_type</td>
<td>db_connection_name</td>
<td>db_snippet_connection</td>
<td>db_data_connection</td>
<td>db_host</td>
<td>db_database</td>
<td>db_username</td>
<td>db_password</td>
<td>db_charset</td>
<td>db_collation</td>
<td>db_prefix</td>
<td>db_driver</td>
<td>generated_files_folder</td>
<td>field_name</td>
<td>id</td>
</tr>
