<tr>
<td>#</td>
<td>db_connection_name</td>
<td>db_data_connection</td>
<td>db_snippet_connection</td>
<td>db_database</td>
<td>db_default</td>
<td>db_driver</td>
<td>db_host</td>
<td>db_password</td>
<td>db_prefix</td>
<td>db_schema</td>
<td>db_username</td>
</tr>
