<tr>
<td>#</td>
<td>table_controller_exists</td>
<td>table_name</td>
<td>controller_name</td>
<td>record_type</td>
<td>db_connection_name</td>
<td>model</td>
<td>model_table</td>
<td>node_name</td>
<td>snippet_table</td>
<td>snippet_table_key_field_name</td>
<td>key_field_name</td>
</tr>
