<tr>
<td>#</td>
<td>report_name</td>
<td>id</td>
<td>created_at</td>
<td>business_rules</td>
<td>business_rules_field_name_array</td>
<td>business_rules_r_o_array</td>
<td>business_rules_value_array</td>
</tr>
